export { default as Header } from './Header'
export { default as Body } from './Body'
export { default as RestaurantCard } from './RestaurantCard'
export { default as Shimmer } from './Shimmer'
export { default as About } from './About'
export { default as Contact } from './Contact'
